"""
Script thêm thông số kỹ thuật vào final_merged_all_fixed.json
Ghép specs từ catalog vào từng sản phẩm dựa trên tên model.
"""
import json
import re
import os

INPUT_FILE  = "final_merged_all_fixed.json"
OUTPUT_FILE = "final_merged_all_fixed.json"   # Ghi đè luôn (đã có backup không?)

# ── SPECS CATALOG ─────────────────────────────────────────────────────────────
SPECS_CATALOG = {
    # ── IPHONE ────────────────────────────────────────────────────────────────
    "iPhone 17 Pro Max": {
        "chip": "Apple A19 Pro",
        "ram": "12GB",
        "screen": "6.9\" Super Retina XDR OLED",
        "battery": "5088 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "48MP",
        "camera_tele": "48MP (5x Optical)",
        "camera_front": "24MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "213g",
        "water_resistance": "IP68",
    },
    "iPhone 17 Pro": {
        "chip": "Apple A19 Pro",
        "ram": "12GB",
        "screen": "6.3\" Super Retina XDR OLED",
        "battery": "4252 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "48MP",
        "camera_tele": "48MP (5x Optical)",
        "camera_front": "24MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "199g",
        "water_resistance": "IP68",
    },
    "iPhone 17": {
        "chip": "Apple A19",
        "ram": "8GB",
        "screen": "6.3\" Super Retina XDR OLED",
        "battery": "3988 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "48MP",
        "camera_front": "24MP",
        "refresh_rate": "120Hz (ProMotion)",
        "weight": "177g",
        "water_resistance": "IP68",
    },
    "iPhone 16 Pro Max": {
        "chip": "Apple A18 Pro",
        "ram": "8GB",
        "screen": "6.9\" Super Retina XDR OLED",
        "battery": "4685 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "48MP",
        "camera_tele": "12MP (5x Optical)",
        "camera_front": "12MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "227g",
        "water_resistance": "IP68",
    },
    "iPhone 16 Pro": {
        "chip": "Apple A18 Pro",
        "ram": "8GB",
        "screen": "6.3\" Super Retina XDR OLED",
        "battery": "3582 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "48MP",
        "camera_tele": "12MP (5x Optical)",
        "camera_front": "12MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "199g",
        "water_resistance": "IP68",
    },
    "iPhone 16 Plus": {
        "chip": "Apple A18",
        "ram": "8GB",
        "screen": "6.7\" Super Retina XDR OLED",
        "battery": "4674 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "203g",
        "water_resistance": "IP68",
    },
    "iPhone 16e": {
        "chip": "Apple A18",
        "ram": "8GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3227 mAh",
        "camera_main": "48MP Fusion",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "167g",
        "water_resistance": "IP68",
    },
    "iPhone 16": {
        "chip": "Apple A18",
        "ram": "8GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3561 mAh",
        "camera_main": "48MP Fusion",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "170g",
        "water_resistance": "IP68",
    },
    "iPhone 15 Pro Max": {
        "chip": "Apple A17 Pro",
        "ram": "8GB",
        "screen": "6.7\" Super Retina XDR OLED",
        "battery": "4422 mAh",
        "camera_main": "48MP",
        "camera_ultra": "12MP",
        "camera_tele": "12MP (5x Optical)",
        "camera_front": "12MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "221g",
        "water_resistance": "IP68",
    },
    "iPhone 15 Pro": {
        "chip": "Apple A17 Pro",
        "ram": "8GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3274 mAh",
        "camera_main": "48MP",
        "camera_ultra": "12MP",
        "camera_tele": "12MP (3x Optical)",
        "camera_front": "12MP",
        "refresh_rate": "120Hz (LTPO ProMotion)",
        "weight": "187g",
        "water_resistance": "IP68",
    },
    "iPhone 15 Plus": {
        "chip": "Apple A16 Bionic",
        "ram": "6GB",
        "screen": "6.7\" Super Retina XDR OLED",
        "battery": "4383 mAh",
        "camera_main": "48MP",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "201g",
        "water_resistance": "IP68",
    },
    "iPhone 15": {
        "chip": "Apple A16 Bionic",
        "ram": "6GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3349 mAh",
        "camera_main": "48MP",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "171g",
        "water_resistance": "IP68",
    },
    "iPhone 14 Plus": {
        "chip": "Apple A15 Bionic",
        "ram": "6GB",
        "screen": "6.7\" Super Retina XDR OLED",
        "battery": "4323 mAh",
        "camera_main": "12MP",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "203g",
        "water_resistance": "IP68",
    },
    "iPhone 14": {
        "chip": "Apple A15 Bionic (5-core GPU)",
        "ram": "6GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3279 mAh",
        "camera_main": "12MP",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "172g",
        "water_resistance": "IP68",
    },
    "iPhone 13": {
        "chip": "Apple A15 Bionic (4-core GPU)",
        "ram": "4GB",
        "screen": "6.1\" Super Retina XDR OLED",
        "battery": "3227 mAh",
        "camera_main": "12MP",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "refresh_rate": "60Hz",
        "weight": "174g",
        "water_resistance": "IP68",
    },

    # ── SAMSUNG ───────────────────────────────────────────────────────────────
    "Samsung Galaxy S25 Ultra": {
        "chip": "Snapdragon 8 Elite for Galaxy (3nm)",
        "ram": "12GB",
        "screen": "6.9\" Dynamic AMOLED 2X, QHD+ 3120x1440, 1-120Hz, 2600 nits",
        "camera_main": "200MP F1.7 OIS",
        "camera_ultra": "50MP F1.9",
        "camera_tele": "50MP (5x) + 10MP (3x)",
        "camera_front": "12MP F2.2",
        "battery": "5000 mAh (45W wired, 15W wireless)",
        "weight": "218g",
        "water_resistance": "IP68",
        "special": "Titanium Frame, Built-in S Pen",
    },
    "Samsung Galaxy S25 Plus": {
        "chip": "Snapdragon 8 Elite / Exynos 2500",
        "ram": "12GB",
        "screen": "6.7\" Dynamic AMOLED 2X, QHD+, 1-120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "12MP",
        "battery": "4900 mAh (45W)",
        "weight": "190g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S25 Edge": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.7\" Dual-Edge AMOLED, QHD+, 1-120Hz",
        "camera_main": "200MP OIS",
        "camera_ultra": "12MP",
        "camera_front": "12MP",
        "battery": "3900 mAh",
        "weight": "163g",
        "dimensions": "158.2 x 75.6 x 5.8 mm",
        "water_resistance": "IP68",
        "special": "Ultra-slim design",
    },
    "Samsung Galaxy S25 FE": {
        "chip": "Exynos 2500e",
        "ram": "8GB",
        "screen": "6.7\" Dynamic AMOLED 2X, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "8MP (3x)",
        "camera_front": "10MP",
        "battery": "4700 mAh",
        "weight": "210g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S25": {
        "chip": "Snapdragon 8 Elite / Exynos 2500",
        "ram": "12GB",
        "screen": "6.2\" Dynamic AMOLED 2X, FHD+, 1-120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "12MP",
        "battery": "4000 mAh (25W)",
        "weight": "162g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S24 Ultra": {
        "chip": "Snapdragon 8 Gen 3 for Galaxy",
        "ram": "12GB",
        "screen": "6.8\" Dynamic AMOLED 2X, QHD+, 1-120Hz",
        "camera_main": "200MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "50MP (5x) + 10MP (3x)",
        "camera_front": "12MP",
        "battery": "5000 mAh (45W)",
        "weight": "232g",
        "water_resistance": "IP68",
        "special": "Titanium Frame, Built-in S Pen",
    },
    "Samsung Galaxy S24 FE": {
        "chip": "Exynos 2400e",
        "ram": "8GB",
        "screen": "6.7\" Dynamic AMOLED 2X, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "8MP (3x)",
        "camera_front": "10MP",
        "battery": "4700 mAh (25W)",
        "weight": "213g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S23 Ultra": {
        "chip": "Snapdragon 8 Gen 2 for Galaxy",
        "ram": "8GB",
        "screen": "6.8\" Dynamic AMOLED 2X, QHD+, 1-120Hz",
        "camera_main": "200MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (10x) + 10MP (3x)",
        "camera_front": "12MP",
        "battery": "5000 mAh (45W)",
        "weight": "234g",
        "water_resistance": "IP68",
        "special": "Built-in S Pen",
    },
    "Samsung Galaxy S23 Plus": {
        "chip": "Snapdragon 8 Gen 2 for Galaxy",
        "ram": "8GB",
        "screen": "6.6\" Dynamic AMOLED 2X, FHD+, 1-120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "12MP",
        "battery": "4700 mAh (45W)",
        "weight": "196g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S23 FE": {
        "chip": "Snapdragon 8 Gen 1 / Exynos 2200",
        "ram": "8GB",
        "screen": "6.4\" Dynamic AMOLED 2X, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "8MP (3x)",
        "camera_front": "10MP",
        "battery": "4500 mAh (25W)",
        "weight": "209g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy S22": {
        "chip": "Snapdragon 8 Gen 1 / Exynos 2200",
        "ram": "8GB",
        "screen": "6.1\" Dynamic AMOLED 2X, FHD+, 1-120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "10MP",
        "battery": "3700 mAh (25W)",
        "weight": "167g",
        "water_resistance": "IP68",
    },
    "Samsung Galaxy Z Fold7": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "8.0\" Dynamic AMOLED 2X, 120Hz (main) + 6.5\" 120Hz (cover)",
        "camera_main": "200MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "10MP",
        "battery": "4400 mAh",
        "thickness": "4.2mm (unfolded)",
        "water_resistance": "IP48",
    },
    "Samsung Galaxy Z Fold6": {
        "chip": "Snapdragon 8 Gen 3 for Galaxy",
        "ram": "12GB",
        "screen": "7.6\" Dynamic AMOLED 2X, 120Hz (main) + 6.3\" 120Hz (cover)",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "10MP (3x)",
        "camera_front": "10MP",
        "battery": "4400 mAh",
        "water_resistance": "IP48",
    },
    "Samsung Galaxy Z Fold5": {
        "chip": "Snapdragon 8 Gen 2 for Galaxy",
        "ram": "12GB",
        "screen": "7.6\" Dynamic AMOLED 2X, 120Hz (main) + 6.2\" 120Hz (cover)",
        "camera_main": "50MP OIS",
        "battery": "4400 mAh",
        "water_resistance": "IPX8",
    },
    "Samsung Galaxy Z Flip7": {
        "chip": "Exynos 2500 / Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.9\" Dynamic AMOLED 2X, 120Hz (main) + 4.1\" Super AMOLED 120Hz (cover)",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_front": "10MP",
        "battery": "4300 mAh",
        "weight": "188g",
        "water_resistance": "IP48",
    },
    "Samsung Galaxy Z Flip6": {
        "chip": "Snapdragon 8 Gen 3 for Galaxy",
        "ram": "12GB",
        "screen": "6.7\" Dynamic AMOLED 2X, 120Hz (main) + 3.4\" Super AMOLED (cover)",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_front": "10MP",
        "battery": "4000 mAh",
        "water_resistance": "IP48",
    },
    "Samsung Galaxy Z Flip5": {
        "chip": "Snapdragon 8 Gen 2 for Galaxy",
        "ram": "8GB",
        "screen": "6.7\" Dynamic AMOLED 2X, 120Hz (main) + 3.4\" Super AMOLED (cover)",
        "camera_main": "12MP OIS",
        "camera_ultra": "12MP",
        "camera_front": "10MP",
        "battery": "3700 mAh",
        "water_resistance": "IPX8",
    },
    "Samsung Galaxy A56": {
        "chip": "Exynos 1580",
        "ram": "8GB",
        "screen": "6.7\" Super AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "12MP",
        "camera_macro": "5MP",
        "camera_front": "12MP Super HDR",
        "battery": "5000 mAh (45W)",
        "water_resistance": "IP67",
    },
    "Samsung Galaxy A36": {
        "chip": "Snapdragon 6 Gen 3",
        "ram": "8GB",
        "screen": "6.7\" Super AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "12MP",
        "battery": "5000 mAh (25W)",
        "water_resistance": "IP67",
    },
    "Samsung Galaxy A26": {
        "chip": "Exynos 850",
        "ram": "8GB",
        "screen": "6.7\" Super AMOLED, FHD+, 120Hz",
        "camera_main": "50MP",
        "camera_ultra": "8MP",
        "camera_front": "13MP",
        "battery": "5000 mAh (25W)",
        "water_resistance": "IP54",
    },
    "Samsung Galaxy A17 5G": {
        "chip": "Exynos 1330",
        "ram": "8GB",
        "screen": "6.7\" TFT LCD, FHD+, 90Hz",
        "camera_main": "50MP",
        "camera_ultra": "8MP",
        "camera_front": "13MP",
        "battery": "5000 mAh (25W)",
    },
    "Samsung Galaxy A17": {
        "chip": "Helio G88",
        "ram": "8GB",
        "screen": "6.7\" TFT LCD, FHD+, 90Hz",
        "camera_main": "50MP",
        "camera_ultra": "8MP",
        "camera_front": "13MP",
        "battery": "5000 mAh",
    },
    "Samsung Galaxy A16": {
        "chip": "Helio G85",
        "ram": "4GB",
        "screen": "6.7\" PLS TFT LCD, FHD+, 90Hz",
        "camera_main": "50MP",
        "camera_front": "13MP",
        "battery": "5000 mAh",
    },
    "Samsung Galaxy A07": {
        "chip": "Exynos 850",
        "ram": "4GB",
        "screen": "6.6\" PLS LCD, FHD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "13MP",
        "battery": "5000 mAh",
    },
    "Samsung Galaxy A06": {
        "chip": "Helio G85",
        "ram": "4GB",
        "screen": "6.7\" PLS TFT LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "8MP",
        "battery": "5000 mAh",
    },
    "Samsung Galaxy A25": {
        "chip": "Exynos 1280",
        "ram": "6GB",
        "screen": "6.5\" Super AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "13MP",
        "battery": "5000 mAh (25W)",
    },
    "Samsung Galaxy M54": {
        "chip": "Exynos 1380",
        "ram": "8GB",
        "screen": "6.7\" Super AMOLED+, FHD+, 120Hz",
        "camera_main": "108MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "32MP",
        "battery": "6000 mAh (25W)",
    },

    # ── XIAOMI ────────────────────────────────────────────────────────────────
    "Xiaomi 15 Ultra": {
        "chip": "Snapdragon 8 Elite",
        "ram": "16GB",
        "screen": "6.78\" LTPO AMOLED, 2K, 1-144Hz",
        "camera_main": "50MP 1-inch sensor (Leica Optic)",
        "camera_ultra": "50MP",
        "camera_tele": "200MP Periscope (5x Optical)",
        "camera_front": "32MP",
        "battery": "5500 mAh (120W wired, 80W wireless)",
        "weight": "226g",
        "water_resistance": "IP69",
    },
    "Xiaomi 15T Pro": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.67\" AMOLED, 1.5K, 144Hz",
        "camera_main": "50MP OIS (Leica)",
        "camera_ultra": "50MP",
        "camera_tele": "50MP (2.5x)",
        "camera_front": "32MP",
        "battery": "5400 mAh (120W)",
        "weight": "213g",
        "water_resistance": "IP68",
    },
    "Xiaomi 15T": {
        "chip": "Dimensity 9300+",
        "ram": "12GB",
        "screen": "6.67\" AMOLED, 1.5K, 144Hz",
        "camera_main": "50MP OIS (Leica)",
        "camera_ultra": "12MP",
        "camera_front": "32MP",
        "battery": "5000 mAh (67W)",
        "weight": "193g",
        "water_resistance": "IP68",
    },
    "Xiaomi 15": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.36\" Flat AMOLED, 1.5K, 1-120Hz",
        "camera_main": "50MP (Leica Optic)",
        "camera_ultra": "50MP",
        "camera_tele": "50MP (2.6x)",
        "camera_front": "32MP",
        "battery": "5240 mAh (90W)",
        "weight": "191g",
        "water_resistance": "IP68",
    },
    "Xiaomi 14 Ultra": {
        "chip": "Snapdragon 8 Gen 3",
        "ram": "16GB",
        "screen": "6.73\" LTPO AMOLED, WQHD+, 1-120Hz",
        "camera_main": "50MP 1-inch LYT-900 (Leica)",
        "camera_ultra": "50MP",
        "camera_tele": "50MP (5x) + 50MP (3.2x)",
        "camera_front": "32MP",
        "battery": "5000 mAh (90W)",
        "weight": "219g",
        "water_resistance": "IP68",
    },
    "Xiaomi 13 Pro": {
        "chip": "Snapdragon 8 Gen 2",
        "ram": "12GB",
        "screen": "6.73\" LTPO AMOLED, WQHD+, 1-120Hz",
        "camera_main": "50MP 1-inch (Leica)",
        "battery": "4820 mAh (120W)",
        "water_resistance": "IP68",
    },
    "Xiaomi 13 Lite": {
        "chip": "Snapdragon 7 Gen 1",
        "ram": "8GB",
        "screen": "6.55\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP",
        "battery": "4500 mAh (67W)",
    },
    "Xiaomi Redmi Note 15 Pro": {
        "chip": "Dimensity 8400 Ultra",
        "ram": "12GB",
        "screen": "6.67\" AMOLED, FHD+, 1-120Hz",
        "camera_main": "200MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "20MP",
        "battery": "5100 mAh (90W)",
        "water_resistance": "IP64",
    },
    "Xiaomi Redmi Note 15 5G": {
        "chip": "Dimensity 7025 Ultra",
        "ram": "6GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP",
        "camera_front": "13MP",
        "battery": "5110 mAh (45W)",
    },
    "Xiaomi Redmi Note 15": {
        "chip": "Helio G100 Ultra",
        "ram": "6GB",
        "screen": "6.7\" AMOLED, FHD+, 120Hz",
        "camera_main": "108MP",
        "camera_front": "20MP",
        "battery": "5160 mAh (33W)",
    },
    "Xiaomi Redmi Note 14 Pro Plus 5G": {
        "chip": "Dimensity 9200+",
        "ram": "8GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "200MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "20MP",
        "battery": "5110 mAh (90W)",
        "water_resistance": "IP68",
    },
    "Xiaomi Redmi Note 14 5G": {
        "chip": "Snapdragon 7s Gen 3",
        "ram": "8GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "108MP OIS",
        "camera_front": "16MP",
        "battery": "5500 mAh (45W)",
    },
    "Xiaomi Redmi Note 14": {
        "chip": "Helio G100 Ultra",
        "ram": "6GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "108MP",
        "camera_front": "16MP",
        "battery": "5500 mAh (33W)",
    },
    "Xiaomi Redmi 15 5G": {
        "chip": "Snapdragon 4s Gen 2",
        "ram": "8GB",
        "screen": "6.88\" IPS LCD, HD+, 90Hz",
        "camera_main": "50MP",
        "camera_front": "5MP",
        "battery": "5160 mAh (18W)",
    },
    "Xiaomi Redmi 15C": {
        "chip": "Helio G81 Ultra",
        "ram": "4GB",
        "screen": "6.88\" IPS LCD, HD+, 90Hz",
        "camera_main": "50MP",
        "camera_front": "5MP",
        "battery": "5160 mAh (10W)",
    },
    "Xiaomi Redmi 13x": {
        "chip": "Helio G91-Ultra",
        "ram": "8GB",
        "screen": "6.79\" IPS LCD, FHD+, 90Hz",
        "camera_main": "108MP",
        "camera_front": "13MP",
        "battery": "5030 mAh (18W)",
    },
    "Xiaomi POCO M7 Pro 5G": {
        "chip": "Dimensity 7025 Ultra",
        "ram": "8GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP",
        "camera_front": "13MP",
        "battery": "5110 mAh (45W)",
    },
    "Xiaomi POCO M7": {
        "chip": "Helio G100 / Dimensity 6300",
        "ram": "6GB",
        "screen": "6.79\" IPS LCD, FHD+, 90Hz",
        "camera_main": "50MP",
        "camera_front": "13MP",
        "battery": "5000 mAh (18W)",
    },
    "Xiaomi POCO M6": {
        "chip": "Helio G85",
        "ram": "8GB",
        "screen": "6.79\" IPS LCD, FHD+, 90Hz",
        "camera_main": "64MP",
        "camera_front": "16MP",
        "battery": "5000 mAh (18W)",
    },
    "Xiaomi Poco X7": {
        "chip": "Dimensity 8400 Ultra",
        "ram": "8GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_front": "20MP",
        "battery": "5200 mAh (45W)",
    },

    # ── OPPO ──────────────────────────────────────────────────────────────────
    "OPPO Find X9 Pro": {
        "chip": "Snapdragon 8 Elite",
        "ram": "16GB",
        "screen": "6.82\" Quad-Curved AMOLED, 2K, 120Hz",
        "camera_main": "50MP LYT-900 OIS (Hasselblad)",
        "camera_ultra": "50MP",
        "camera_tele": "50MP (3x) + 50MP Periscope (6x)",
        "camera_front": "32MP",
        "battery": "5400 mAh (100W)",
        "special": "Satellite Communication",
        "water_resistance": "IP68",
    },
    "OPPO Find X9": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.78\" OLED, 2K, 120Hz",
        "camera_main": "50MP OIS (Hasselblad)",
        "camera_ultra": "50MP",
        "camera_tele": "50MP (3x)",
        "camera_front": "32MP",
        "battery": "5400 mAh (80W)",
        "water_resistance": "IP68",
    },
    "OPPO Find N5": {
        "chip": "Snapdragon 8 Elite",
        "ram": "16GB",
        "screen": "7.8\" Foldable OLED (main) + 6.24\" cover",
        "camera_main": "50MP OIS",
        "battery": "5600 mAh",
        "weight": "229g",
        "special": "Lightest horizontal foldable",
    },
    "OPPO Find N3": {
        "chip": "Snapdragon 8 Gen 2",
        "ram": "16GB",
        "screen": "7.82\" Foldable OLED 120Hz (main)",
        "camera_main": "48MP OIS",
        "camera_ultra": "48MP",
        "camera_tele": "20MP (6x Periscope)",
        "battery": "4800 mAh (67W)",
        "weight": "245g",
    },
    "OPPO Reno15": {
        "chip": "Dimensity 8300-Max",
        "ram": "12GB",
        "screen": "6.78\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "8MP",
        "camera_front": "50MP AF",
        "battery": "5000 mAh (80W)",
        "special": "AI Portrait Expert",
    },
    "OPPO Reno15 F": {
        "chip": "Dimensity 7300",
        "ram": "8GB",
        "screen": "6.7\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_front": "32MP",
        "battery": "5000 mAh (45W)",
    },
    "OPPO A5i Pro": {
        "chip": "Helio G91",
        "ram": "8GB",
        "screen": "6.72\" IPS LCD, FHD+, 120Hz",
        "camera_main": "50MP",
        "camera_front": "8MP",
        "battery": "5000 mAh (15W)",
    },
    "OPPO A6T": {
        "chip": "Helio G85",
        "ram": "6GB",
        "screen": "6.72\" IPS LCD, FHD+, 90Hz",
        "camera_main": "50MP",
        "camera_front": "8MP",
        "battery": "5000 mAh",
    },
    "OPPO A5i": {
        "chip": "Helio G81",
        "ram": "6GB",
        "screen": "6.67\" IPS LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "5MP",
        "battery": "5000 mAh",
    },
    "OPPO A18": {
        "chip": "Helio G85",
        "ram": "4GB",
        "screen": "6.56\" IPS LCD, HD+, 60Hz",
        "camera_main": "8MP",
        "camera_front": "5MP",
        "battery": "5000 mAh",
    },

    # ── HONOR ─────────────────────────────────────────────────────────────────
    "Honor Magic V5": {
        "chip": "Snapdragon 8 Elite",
        "ram": "16GB",
        "screen": "8.02\" Foldable OLED 120Hz (main) + 6.45\" cover",
        "camera_main": "50MP OIS",
        "camera_ultra": "40MP",
        "camera_tele": "40MP (4x Periscope)",
        "battery": "5150 mAh (100W)",
        "thickness_folded": "9.1mm",
        "special": "Slimmest foldable",
    },
    "Honor 400 Pro": {
        "chip": "Snapdragon 8s Gen 4",
        "ram": "12GB",
        "screen": "6.78\" OLED, 1.5K, 120Hz, 4320Hz PWM",
        "camera_main": "200MP OIS",
        "camera_ultra": "12MP",
        "camera_tele": "50MP (3x)",
        "camera_front": "50MP",
        "battery": "5300 mAh (100W)",
        "water_resistance": "IP65",
    },
    "Honor 400": {
        "chip": "Snapdragon 7s Gen 3",
        "ram": "12GB",
        "screen": "6.7\" OLED, FHD+, 120Hz",
        "camera_main": "200MP OIS",
        "camera_front": "16MP",
        "battery": "5200 mAh (66W)",
        "water_resistance": "IP65",
    },
    "Honor 400 Lite": {
        "chip": "Snapdragon 6 Gen 1",
        "ram": "12GB",
        "screen": "6.7\" OLED, FHD+, 90Hz",
        "camera_main": "108MP",
        "camera_front": "16MP",
        "battery": "5000 mAh (35W)",
    },
    "Honor 200": {
        "chip": "Snapdragon 7s Gen 2",
        "ram": "12GB",
        "screen": "6.7\" OLED, 1.5K, 120Hz",
        "camera_main": "50MP OIS (Harcourt portrait)",
        "camera_tele": "50MP (2.5x)",
        "camera_front": "50MP",
        "battery": "5200 mAh (100W)",
        "water_resistance": "IP54",
    },
    "Honor X9d": {
        "chip": "Snapdragon 6 Gen 1",
        "ram": "8GB",
        "screen": "6.78\" OLED, 1.5K, 120Hz",
        "camera_main": "108MP OIS",
        "camera_front": "16MP",
        "battery": "5500 mAh (35W)",
    },
    "Honor X8c": {
        "chip": "Snapdragon 4 Gen 2",
        "ram": "8GB",
        "screen": "6.7\" OLED, FHD+, 90Hz",
        "camera_main": "108MP",
        "camera_front": "16MP",
        "battery": "4500 mAh (35W)",
    },
    "Honor X7d": {
        "chip": "Helio G85",
        "ram": "8GB",
        "screen": "6.8\" IPS LCD, FHD+, 90Hz",
        "camera_main": "108MP",
        "camera_front": "8MP",
        "battery": "6000 mAh (35W)",
    },
    "Honor X6c": {
        "chip": "Helio G85",
        "ram": "6GB",
        "screen": "6.8\" IPS LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "5MP",
        "battery": "5200 mAh",
    },
    "Honor X5c Plus": {
        "chip": "Helio G36",
        "ram": "4GB",
        "screen": "6.74\" IPS LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "5MP",
        "battery": "5200 mAh",
    },

    # ── REDMAGIC ──────────────────────────────────────────────────────────────
    "RedMagic 11 Pro": {
        "chip": "Snapdragon 8 Elite (Active Cooling Fan)",
        "ram": "12GB",
        "screen": "6.8\" Under-display Camera AMOLED, FHD+, 165Hz",
        "camera_main": "50MP OIS",
        "camera_ultra": "50MP",
        "camera_front": "16MP (under-display)",
        "battery": "6500 mAh (165W)",
        "special": "Gaming phone with built-in cooling fan",
    },
    "RedMagic 10S Pro": {
        "chip": "Snapdragon 8 Elite",
        "ram": "12GB",
        "screen": "6.85\" AMOLED, FHD+, 144Hz",
        "camera_main": "50MP OIS",
        "camera_front": "16MP",
        "battery": "6500 mAh (120W)",
        "special": "Gaming phone with active cooling",
    },

    # ── TECNO ─────────────────────────────────────────────────────────────────
    "TECNO POVA 7": {
        "chip": "Dimensity 7200",
        "ram": "8GB",
        "screen": "6.8\" IPS LCD, FHD+, 120Hz",
        "camera_main": "108MP",
        "camera_front": "16MP",
        "battery": "7000 mAh (33W)",
        "special": "Super Battery",
    },
    "TECNO POVA 6": {
        "chip": "Helio G99",
        "ram": "8GB",
        "screen": "6.78\" IPS LCD, FHD+, 120Hz",
        "camera_main": "108MP",
        "camera_front": "32MP",
        "battery": "6000 mAh (45W)",
    },

    # ── NUBIA ─────────────────────────────────────────────────────────────────
    "Nubia Air 5G": {
        "chip": "Snapdragon 7 Gen 3",
        "ram": "8GB",
        "screen": "6.78\" AMOLED, FHD+, 144Hz",
        "camera_main": "50MP",
        "camera_front": "16MP",
        "battery": "5000 mAh (80W)",
        "weight": "163g",
        "special": "Ultra-slim 5.9mm",
    },
    "Nubia V80 Design": {
        "chip": "Unisoc T7280",
        "ram": "8GB",
        "screen": "6.75\" IPS LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "8MP",
        "battery": "6000 mAh",
        "special": "NFC",
    },
    "Nubia V80 Max": {
        "chip": "Unisoc T618",
        "ram": "8GB",
        "screen": "6.9\" IPS LCD, HD+, 60Hz",
        "camera_main": "50MP",
        "camera_front": "8MP",
        "battery": "6000 mAh",
        "special": "NFC",
    },

    # ── REALME ────────────────────────────────────────────────────────────────
    "Realme 13+ 5G": {
        "chip": "Dimensity 7300 Energy",
        "ram": "8GB",
        "screen": "6.67\" AMOLED, FHD+, 120Hz",
        "camera_main": "50MP OIS",
        "camera_front": "16MP",
        "battery": "5000 mAh (80W)",
        "water_resistance": "IP65",
    },
}


# ── MATCHING LOGIC ────────────────────────────────────────────────────────────
def normalize(text: str) -> str:
    """Chuẩn hoá: lowercase, bỏ ký tự đặc biệt."""
    text = re.sub(r'[^a-z0-9 ]', ' ', text.lower())
    return re.sub(r'\s+', ' ', text).strip()


def get_specs(product_name: str) -> dict | None:
    """
    Tìm specs phù hợp nhất cho tên sản phẩm.
    Ưu tiên model dài hơn để tránh nhầm (VD: S25 vs S25 Ultra).
    """
    norm_name = normalize(product_name)
    best_key = None
    best_len = 0

    for catalog_key in SPECS_CATALOG:
        norm_key = normalize(catalog_key)
        if norm_key in norm_name and len(norm_key) > best_len:
            best_key = catalog_key
            best_len = len(norm_key)

    return SPECS_CATALOG[best_key].copy() if best_key else None


# ── MAIN ──────────────────────────────────────────────────────────────────────
def main():
    if not os.path.exists(INPUT_FILE):
        print(f"❌ Không tìm thấy {INPUT_FILE}")
        return

    with open(INPUT_FILE, "r", encoding="utf-8") as f:
        products = json.load(f)

    updated = 0
    skipped = 0

    for p in products:
        name = p.get("name", "")
        specs = get_specs(name)
        if specs:
            p["specs"] = specs
            updated += 1
        else:
            skipped += 1

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        json.dump(products, f, ensure_ascii=False, indent=2)

    print("Done!")
    print(f"   Added specs : {updated} products")
    print(f"   No match    : {skipped} products")
    print(f"   Saved to    : {OUTPUT_FILE}")


if __name__ == "__main__":
    main()
